package model;

import java.util.ArrayList;
import java.util.Random;
/**
 * The Generate-Class generates a new nickname. It includes the ABC, the given structure of the nickname which should be created
 * and a String where the created nickname gets saved.
 * @author zzaxec
 *
 */
public class Generator {
	
	Alphabet alphabet;
	private ArrayList<String> nickStrukt;
	private String nickname;
	
	// Constructor
	public Generator() {
		alphabet = new Alphabet();
	}

	
	/*
	 * GETTER AND SETTER
	 */
	public Alphabet getAlphabet() {
		return alphabet;
	}

	public String getNickname() {
		return nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}
	
	/*
	 * METHODS FOR GENERATION
	 */
	
	
	/**
	 * 
	 * Returns a nickname which is generated by a specific structure.
	 * @return the generated Nickname as String
	 */
	public String generate(){
		Random r = new Random();
		int zufall;
		String newNickname = "";
		for(int i=0; i<nickStrukt.size(); i++){
			zufall = r.nextInt(26);
			while(!alphabet.getLaut(zufall).equals(nickStrukt.get(i))){
				zufall = r.nextInt(26);
			}
			newNickname += alphabet.getBuchstabe(zufall);
		}
		return newNickname;
	}
	
	/**
	 * Saves every single letter of the given structure in an ArrayList.
	 * Later this Arraylist is handed over the generate-method to create a new nickname.
	 * @param struct the given structure which has to be split
	 */
	public void getStructure(String struct){
		nickStrukt = new ArrayList<String>();
		for(int i=0; i<struct.length(); i++){
			nickStrukt.add(struct.substring(i, i+1));
		}
	}
	
	/**
	 * Removes all the elements of the ArrayList and clears thus the structure to start over.
	 */
	public void löscheArrayList(){
		nickStrukt.clear();
	}
}
